classDiagram


class User {

-Dni

-Nombre

-Apellido

-Telefono

-Email

}


class Student {

}



class Professor {

}


class Subject {

-Codigo

-Nombre

}

  

%% Herencia

User <|-- Student

User <|-- Professor

User <|-- Admin

  

%% Relaciones

  

Professor "1" -- "1..*" Subject : Responsable

Student "*" -- "*" Subject : Inscripcion
