flowchart TB
    U[Usuario]

    subgraph Inicio
        Interfaz[Interfaz Web]
    end

   
    RyC[Rutas y Controladores]
    

    subgraph Aplicacion
        Autenticacion[Autenticacion]
        GestionUs[Manipulador Usuario]
        GestionProf[Manipulador Profesor]
    end

    subgraph Abstraccion
        ModeloUs[Modelo de Usuario]
        ModeloProf[Professor Modelo de Profesor]

        Singleton[DBConfigSingleton]
    end

    DB[(SQLite)]

    U --> Inicio
    Interfaz --> RyC
    RyC --> Autenticacion
    RyC --> GestionUs
    RyC --> GestionProf

    Autenticacion --> ModeloUs
    GestionUs --> ModeloUs
    GestionProf --> ModeloProf


    ModeloUs --> Singleton
    ModeloProf --> Singleton

    Singleton --> DB